export const fields = [
  { value: 'technology', label: 'Technology' },
  { value: 'business', label: 'Business' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'education', label: 'Education' },
  { value: 'engineering', label: 'Engineering' },
  { value: 'finance', label: 'Finance' },
  { value: 'marketing', label: 'Marketing' },
  { value: 'design', label: 'Design' },
  { value: 'science', label: 'Science' },
  { value: 'arts', label: 'Arts' },
  { value: 'law', label: 'Law' },
  { value: 'media', label: 'Media' },
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'manufacturing', label: 'Manufacturing' },
  { value: 'consulting', label: 'Consulting' },
  { value: 'leadership', label: 'Leadership' },
  { value: 'banking', label: 'Banking & Financial Services' },
  { value: 'datascience', label: 'Data Science & AI' },
  { value: 'cybersecurity', label: 'Cybersecurity' },
  { value: 'public_health', label: 'Public Health' },
  { value: 'tourism', label: 'Tourism & Hospitality' },
  { value: 'transport', label: 'Transport & Logistics' },
  { value: 'environment', label: 'Environment & Climate Change' },
  { value: 'energy', label: 'Energy & Renewables' },
  { value: 'governance', label: 'Governance & Public Policy' },
  { value: 'entrepreneurship', label: 'Entrepreneurship' },
  { value: 'project_management', label: 'Project Management' },
  { value: 'accounting', label: 'Accounting & Auditing' },
  { value: 'civil_service', label: 'Civil Service & Administration' },
  { value: 'human_resources', label: 'Human Resources' },
  { value: 'real_estate', label: 'Real Estate' },
  { value: 'creative_industry', label: 'Creative Industry (Music, Arts, Film)' },
  { value: 'supply_chain', label: 'Supply Chain Management' },
  { value: 'international_relations', label: 'International Relations' },
  { value: 'telecommunications', label: 'Telecommunications' },
  { value: 'sports', label: 'Sports & Recreation' },
  { value: 'religious_leadership', label: 'Religious Leadership' },
  { value: 'social_work', label: 'Social Work & Community Development' },
  { value: 'ngo', label: 'NGO & Development Work' },
  { value: 'other', label: 'Other' }
];
